# Generated by Django 3.2 on 2021-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('TE', 'Technology'), ('FO', 'Food'), ('Cl', 'Clothing'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
    ]
