# Generated by Django 3.2 on 2021-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'Any'), ('TE', 'Technology'), ('FO', 'Food'), ('Cl', 'Clothing'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
