# Generated by Django 3.2 on 2021-05-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='photos/default_store.jpg', upload_to='photos/'),
        ),
    ]
