# Generated by Django 3.2 on 2021-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AN', 'category(any)'), ('TE', 'Technology'), ('FO', 'Food'), ('Cl', 'Clothing'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
