# Generated by Django 3.2 on 2021-04-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='money',
            new_name='balance',
        ),
    ]
