# Generated by Django 3.2 on 2021-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_money_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='photos/default_store.jpg', upload_to='photos/'),
        ),
    ]
