# Generated by Django 3.2 on 2021-05-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
    ]
