# Generated by Django 3.2 on 2021-05-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number',
        ),
    ]
