# Generated by Django 3.2 on 2021-05-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
