# Generated by Django 3.2 on 2021-05-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_payhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayHistory',
        ),
    ]
