# Generated by Django 3.2 on 2021-05-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_payhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number',
        ),
    ]
